### ISSUE TITLE
Exam Mode

### ISSUE THREAD

**Issue by palexster** [netgroup-polito/CrownLabs#197]
Objective: CrownLabs is quite effective to host laboratories and manage different courses. Particularly, desktop sharing is very useful to support the work of multiple people at the same time (e.g., teammates), the help from instructors, but also from other people (e.g., other students) who can provide an help to a student who is blocked on some problems.
However, desktop sharing has to be disabled in case of exam, allowing only professors to connect to student's desktop.
So, it would be nice to support an "exam mode" in  CrownLabs, where:

- [ ] Instances are only accessible to candidates and professor for assistance
- [ ] Network traffic with internet and other vms has to be blocked
- [ ] Student should be able to hand in an elaborate (e.g; through Shared Storage)

**Comment by michele6000** [comment]
- We can manage the lock of the students pc with Respondus Lockdown Browser.
- In order to grant no access to internet we can put VMs in a virtual lan, or force the VMs to run only the application that the student need. (e.g. eclipse for programming exams).
- To have any elaborate it's fine to use ShS.

**Comment by frisso** [comment]
@michele6000 VLANs are not available in Kubernetes. Unfortunately, not everything is easy as it appears :-)

**Comment by michele6000** [comment]
Maybe we can try to add a Firewall to VMs?
