### ISSUE TITLE
Roadmap for new front end

### ISSUE THREAD

**Issue by GabriFila** [netgroup-polito/CrownLabs#432]
This issue describes the roadmap/todo for the new frontend.

Roadmap
1. [x] Get user feedback on the previous and current dashboards
    - [x] Build google form
    - [x] Figure out how to send bulk emails
2. [x] Analyze user feedback and set user needs and requirements
    - past fetaures (_to complete_)
    - signal issues to admins
    - get notified of events about instances, cluster status, etc.
    - get in touch with professor through a chat
    - SSH management and access
    - view VM resource template (CPU cores, RAM size)
    - view account information
    - clear distinction between templates and instances
    - clear navigation flow (best effort 😅 )
    - upload files from browser inside instance
    - ease user managament from manager view
    - general info section on the page (website, telegram channel, others...)
3. [x] Build mockups
4. [x] Publish mockups (video) and let users to vote
5. [x] Decide ui-components library: [ant design](https://ant.design/)
5. [x] Define areas to work
    - graphql interface (includes both client code to access to this service, and the backend code required for this pod to work) - Marco Manco
    - main panel (available templates, start a service) - Alessandro Cannarella, Francesco Cheinasso
    - active panel (list of running apps, details about running apps) - Alessandro Cresti
    - user panel and user management (add users, list enrolled and active users - to be decided) - Luca Errani, Alessandro Bacci
    - miscellaneous (dark theme, info, notifications, chat, SSH)
6. [x] Define coding style/rules
7. [x] Create React boilerplate

In the meantime learn about Figma, HTML/CSS/JS and React

**Comment by giorio94** [comment]
Closing, as the first beta has been released.
