### ISSUE TITLE
Instance operator refactoring

### ISSUE THREAD

**Issue by giorio94** [netgroup-polito/CrownLabs#512]
## Overview

This issue summarizes the main tasks towards the instance operator refactoring, for increased robustness and modularity.

## Task list

* [x] Rationalize the usage of the `CreateOrUpdate` function;
* [x] Replace the deprecated `setInstanceStatus` with a single update at the end of the reconcile;
* [X] Replace the custom VM readiness check with a proper readiness probe;
* [X] Move the `DataVolume` definition to the VM spec, instead of a separated object;
* [x] Move all resource definitions to the `forge` package, split in smaller units for easier reuse;
* [x] Migrate to structured logging;
* [x] Increment the test coverage;
* [x] Standardise file/dirs/package names;

### `CreateOrUpdate` guidelines

As for the  `CreateOrUpdate` usage, it is necessary to balance between resource enforcement and user disruption. For this reason, it is suggested the following:
* Do not modify those specs (e.g., deployment/VM templates) which would cause the restart of the user environment;
* Do enforce the various metadata information (labels, annotations, references), while ensuring user values are conserved;
* Vary the approach in the other cases depending on the specific situation, trying to reduce disruption in case the logic changed after a new release. Document whatever approach is selected for future information.

**Comment by giorio94** [comment]
Closing, as fully addressed
