### ISSUE TITLE
CrownLabs for exams - roadmap

### ISSUE THREAD

**Issue by QcFe** [netgroup-polito/CrownLabs#513]
### Concept
- Hardened environment
- Customizable instance startup
- Custom instance endpoint (URL)
- Scalable environment for exercises

### Changes to be done
- [ ] Adapt `Instance` CRD
  - [ ] add _omitempty_ `endpoint` property: Map envName->endpoint
- [ ] Adapt `Template` CRD
  - [ ] add _omitempty_ `containerStartup` property: Contains pre-population archive, pre-population destination and startup script 

### Features to be added
- [ ] Programmatic instance creation (and timed removal) for exercises
- [ ] Widget for user identification & timer
- [ ] InstanceList/Exam operator & generalization
  - [ ] Redirection
  - [ ] User list retrieval
  - [ ] Results collection
