### ISSUE TITLE
Enable arbitrary applications on CrownLabs - Roadmap

### ISSUE THREAD

**Issue by cheina97** [netgroup-polito/CrownLabs#715]
This project is carried out by @cannarelladev and @cheina97 
Phase 1 - Deploy and use a generic HTTP based application on CrownLabs:

- [x] Add Standalone EnvironmentType to the CRD
- [x] Implement the creation of a standalone application's Ingress in the instance controller
- [x] Add the Rewrite annotation to the ingress to allow the deploying of applications with a generic subpath
- [x] Implement the creation of a standalone application's Service in the instance controller
- [x] Implement a new Pod creation function for standalone applications in the instance controller
- [x] Change URL in instance status
- [x] Clean the code
- [x] Add a flag to enable ingress rewrite
- [x] Write tests

Phase 2 - Integrate applications with MyDrive:

- [x] Deploy a sidecar container containing the MyDrive application
- [x] Manage MyDrive path inside Ingress.

Phase 3 - create a custom code-server:

- [x] Pass env variables
- [x] c/c++ extension fix
- [x] MyDrive mount in workspace folder
- [x] Manage container's user security
- [x] separate templates for languages
- [x] setup proxy_domain

Phase 4 - Alternative Modes:

- [x] Test the Persistent behavior with Standalone applications

Phase 5 - Integrate with dashboard

- [x] Add a new type to the EnvironmentTypes enum

**Comment by cheina97** [comment]
The **Standalone Applications** feature has been released.
