### ISSUE TITLE
Automating the completion of GNS3 setup

### ISSUE THREAD

**Issue by fracappa** [netgroup-polito/CrownLabs#852]
**Objective**
The completion of setting of GNS3 software is currently done manually.

**Proposal**
It would be nice if those steps could be done automatically through Ansible.

**Tasks**
Steps to be done are:

- [x] Download the Cisco ISO Image
- [x] Create a new template for Cisco 2691 router
- [x] Configure Xfce4 terminal in GNS3
- [x] Adding network-multitool docker image to the list of end devices

**Comments**
Those tasks might involve the addition of files to specific GNS3 file paths. 
An evaluation should be done in order to detect if those are textual files or binary ones.

In the latter case, uploading the files to a repository and downloading them via Ansible could be the final solution.

**Comment by Otello50** [comment]
cool
